import { inter, poppins } from "./fonts";
import "./globals.css";
import CampaignBanner from "@/components/campaignBanner";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Exclusive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} min-h-screen`}>
        <CampaignBanner />
        <Navbar />
        <div className="">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
