import { poppins } from "../fonts";
import Image from "next/image";
import "../globals.css";

import CampaignBanner from "@/components/campaignBanner";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";
import img from "@/public/images/auth/auth.svg";


export const metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} min-h-screen`}>
        <CampaignBanner />
        <Navbar />
        
        <div className="my-[60px] flex flex-col lg:flex-row gap-y-10">
          <div className="flex items-center justify-center">
            <Image
              src={img}
              alt="Shopping illustration"
              className="w-full h-auto"
            />
          </div>
          <div className="lg:w-1/2 flex items-center justify-center">
          {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
